In [3]:
import pandas as pd
import numpy as np

In [7]:
data = [
    [1, 'Khulan', 78, 90],
    [2, 'Batgerel', 80, 90],
    [3, 'Dhiraj', 78, 90],
    [4, 'Manisha', 88, 76],
    [5, 'Aelita', 56, 90],
]
df = pd.DataFrame(data, columns=['Rollno', 'Name', 'Maths', 'English'])
df

   Rollno      Name  Maths  English
0       1    Khulan     78       90
1       2  Batgerel     80       90
2       3    Dhiraj     78       90
3       4   Manisha     88       76
4       5    Aelita     56       90

# wide long

In [9]:
df_long = df.melt(id_vars=['Rollno', 'Name'],
                 value_vars=['Maths', 'English'],
                 var_name='Subject',
                 value_name='Marks')
df_long

   Rollno      Name  Subject  Marks
0       1    Khulan    Maths     78
1       2  Batgerel    Maths     80
2       3    Dhiraj    Maths     78
3       4   Manisha    Maths     88
4       5    Aelita    Maths     56
5       1    Khulan  English     90
6       2  Batgerel  English     90
7       3    Dhiraj  English     90
8       4   Manisha  English     76
9       5    Aelita  English     90

In [11]:
wide_df = df_long.pivot(index=['Rollno', 'Name'], columns='Subject',
                       values='Marks').reset_index(drop=False).rename_axis(None, axis=1)
wide_df

   Rollno      Name  English  Maths
0       1    Khulan       90     78
1       2  Batgerel       90     80
2       3    Dhiraj       90     78
3       4   Manisha       76     88
4       5    Aelita       90     56

In [12]:
wide_df2 = df_long.pivot_table(index=['Rollno','Name'], columns='Subject',
                               values='Marks', aggfunc='sum').reset_index(drop=False).rename_axis(None, axis=1)
wide_df2

   Rollno      Name  English  Maths
0       1    Khulan       90     78
1       2  Batgerel       90     80
2       3    Dhiraj       90     78
3       4   Manisha       76     88
4       5    Aelita       90     56