In [3]:
import pandas as pd
import numpy as np

In [7]:
data = [
    [1, 'Khulan', 78, 90],
    [2, 'Batgerel', 80, 90],
    [3, 'Dhiraj', 78, 90],
    [4, 'Manisha', 88, 76],
    [5, 'Aelita', 56, 90],
]
df = pd.DataFrame(data, columns=['Rollno', 'Name', 'Maths', 'English'])
df

   Rollno      Name  Maths  English
0       1    Khulan     78       90
1       2  Batgerel     80       90
2       3    Dhiraj     78       90
3       4   Manisha     88       76
4       5    Aelita     56       90

# wide long

In [9]:
df_long = df.melt(id_vars=['Rollno', 'Name'],
                 value_vars=['Maths', 'English'],
                 var_name='Subject',
                 value_name='Marks')
df_long

   Rollno      Name  Subject  Marks
0       1    Khulan    Maths     78
1       2  Batgerel    Maths     80
2       3    Dhiraj    Maths     78
3       4   Manisha    Maths     88
4       5    Aelita    Maths     56
5       1    Khulan  English     90
6       2  Batgerel  English     90
7       3    Dhiraj  English     90
8       4   Manisha  English     76
9       5    Aelita  English     90

In [11]:
wide_df = df_long.pivot(index=['Rollno', 'Name'], columns='Subject',
                       values='Marks').reset_index(drop=False).rename_axis(None, axis=1)
wide_df

   Rollno      Name  English  Maths
0       1    Khulan       90     78
1       2  Batgerel       90     80
2       3    Dhiraj       90     78
3       4   Manisha       76     88
4       5    Aelita       90     56

In [12]:
wide_df2 = df_long.pivot_table(index=['Rollno','Name'], columns='Subject',
                               values='Marks', aggfunc='sum').reset_index(drop=False).rename_axis(None, axis=1)
wide_df2

   Rollno      Name  English  Maths
0       1    Khulan       90     78
1       2  Batgerel       90     80
2       3    Dhiraj       90     78
3       4   Manisha       76     88
4       5    Aelita       90     56

# Group By

In [14]:
df_long.groupby('Subject')['Marks'].agg(['sum', 'mean', 'count'])

         sum  mean  count
Subject
English  436  87.2      5
Maths    380  76.0      5

In [17]:
df[['Maths','English']].mean()

Maths      76.0
English    87.2
dtype: float64

In [18]:
df.dtypes

Rollno      int64
Name       object
Maths       int64
English     int64
dtype: object

In [19]:
df.select_dtypes(include='number').mean()

Rollno      3.0
Maths      76.0
English    87.2
dtype: float64

# Missing Values

In [5]:
import numpy as np
import pandas as pd
data= [
    [1, 'Khulan', None, 90],
    [2, 'Bat', 90,90],
    [3, 'Dhiraj', 80,90],
    [4, 'Manisha', np.nan, 70],
    [5, 'Gerel', np.nan, None],
]
df = pd.DataFrame(data, columns=['Rollno', 'Name', 'Maths','English' ])
df

   Rollno     Name  Maths  English
0       1   Khulan    NaN     90.0
1       2      Bat   90.0     90.0
2       3   Dhiraj   80.0     90.0
3       4  Manisha    NaN     70.0
4       5    Gerel    NaN      NaN

In [6]:
df.isna().sum()

Rollno     0
Name       0
Maths      3
English    1
dtype: int64

In [7]:
df.isna().sum(axis=1)

0    1
1    0
2    0
3    1
4    2
dtype: int64

In [8]:
df.fillna(50)

   Rollno     Name  Maths  English
0       1   Khulan   50.0     90.0
1       2      Bat   90.0     90.0
2       3   Dhiraj   80.0     90.0
3       4  Manisha   50.0     70.0
4       5    Gerel   50.0     50.0

In [9]:
df['Maths'].mean()

np.float64(85.0)

In [11]:
df['Maths'] = df['Maths'].fillna(df['Maths'].mean())
df
#filling data with 85.0

   Rollno     Name  Maths  English
0       1   Khulan   85.0     90.0
1       2      Bat   90.0     90.0
2       3   Dhiraj   80.0     90.0
3       4  Manisha   85.0     70.0
4       5    Gerel   85.0      NaN

In [12]:
df['English'] = df['English'].fillna(df['English'].mean())
df

   Rollno     Name  Maths  English
0       1   Khulan   85.0     90.0
1       2      Bat   90.0     90.0
2       3   Dhiraj   80.0     90.0
3       4  Manisha   85.0     70.0
4       5    Gerel   85.0     85.0

In [13]:
df.loc[df['Rollno']==1,['Maths']] = 88
df.loc[df['Rollno']==3,['Maths','English']] = [100,100]
df

   Rollno     Name  Maths  English
0       1   Khulan   88.0     90.0
1       2      Bat   90.0     90.0
2       3   Dhiraj  100.0    100.0
3       4  Manisha   85.0     70.0
4       5    Gerel   85.0     85.0

In [ ]:
aq_drop = aq.dropna()
aq_fill = aq.copy()
aq_fill['Ozone'] =