# Advanced Panda Functions

In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.set_option('display.max_columns',None)

In [4]:
from pydataset import data
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [5]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [6]:
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [7]:
mtcars = data('mtcars')
mtcars = mtcars.astype({ 'cyl': 'category', 'vs': 'category', 'carb': 'category', 'am': 'category', 'gear': 'category'})

In [8]:
mtcars.dtypes

mpg      float64
cyl     category
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs      category
am      category
gear    category
carb    category
dtype: object

In [9]:
mtcars.head()

                    mpg cyl   disp   hp  drat     wt   qsec vs am gear carb
Mazda RX4          21.0   6  160.0  110  3.90  2.620  16.46  0  1    4    4
Mazda RX4 Wag      21.0   6  160.0  110  3.90  2.875  17.02  0  1    4    4
Datsun 710         22.8   4  108.0   93  3.85  2.320  18.61  1  1    4    1
Hornet 4 Drive     21.4   6  258.0  110  3.08  3.215  19.44  1  0    3    1
Hornet Sportabout  18.7   8  360.0  175  3.15  3.440  17.02  0  0    3    2

In [10]:
mtcars['am'] =mtcars['am'].map({0: 'auto', 1:'manual'})
mtcars.head() #sorting by manual or automatic engine

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2

In [11]:
mtcars['mpg'].max()

33.9

In [11]:
bins = [0, 17, 29, mtcars['mpg'].max()]
labels = ['Low', 'Medium', 'High']

In [12]:
mtcars['mpg_level'] = pd.cut(mtcars['mpg'], bins=bins, labels=labels, include_lowest=True)

In [60]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,4,4,Medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,4,4,Medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,4,1,Medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1,Medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2,Medium

In [13]:
mtcars.groupby('mpg_level')['mpg'].count()

/var/folders/w6/x5twkjq11wnbvlzkldcqbgwc0000gn/T/ipykernel_62937/4182853279.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mtcars.groupby('mpg_level')['mpg'].count()

mpg_level
Low       11
Medium    17
High       4
Name: mpg, dtype: int64

In [14]:
mtcars.mpg_level.value_counts()

mpg_level
Medium    17
Low       11
High       4
Name: count, dtype: int64

In [15]:
mtcars['vs'] = mtcars['vs'].map({0: 'Vshaped', 1:'Straight'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium

In [16]:
mtcars.reset_index()

,index,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,Medium
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,Low
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,Straight,auto,4,2,Medium
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,Medium
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,Medium
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,Medium
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,Low
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,Medium
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,Low
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,Low
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,Low
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,Low
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,High
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,High
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,High
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,Medium
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,Low
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,Low
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,Low
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,Medium
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,Medium
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,Medium
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,High
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,Low
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,Medium
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,Low
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,Medium

In [65]:
mtcars.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230',
       'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL', 'Merc 450SLC',
       'Cadillac Fleetwood', 'Lincoln Continental', 'Chrysler Imperial',
       'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird',
       'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L',
       'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype='object')

In [66]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium

In [67]:
mtcars['car_name'] = mtcars.index
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,car_name
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,Hornet Sportabout

In [68]:
mtcars['model'] = mtcars.index #carnames & model & carno.

In [69]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,car_name,model
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium,Mazda RX4,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium,Mazda RX4 Wag,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium,Datsun 710,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Hornet 4 Drive,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,Hornet Sportabout,Hornet Sportabout

In [70]:
mtcars.dtypes

mpg           float64
cyl          category
disp          float64
hp              int64
drat          float64
wt            float64
qsec          float64
vs           category
am           category
gear         category
carb         category
mpg_level    category
car_name       object
model          object
dtype: object

In [71]:
print(len(mtcars[mtcars['mpg'] > 25]))

6

In [72]:
mtcars[mtcars['mpg'] > 25]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,car_name,model
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,High,Fiat 128,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,High,Honda Civic,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,High,Toyota Corolla,Toyota Corolla
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,Straight,manual,4,1,Medium,Fiat X1-9,Fiat X1-9
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,Vshaped,manual,5,2,Medium,Porsche 914-2,Porsche 914-2
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,High,Lotus Europa,Lotus Europa

In [73]:
mtcars[mtcars['wt'] >= 5]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,car_name,model
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,Low,Cadillac Fleetwood,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,Low,Lincoln Continental,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,Low,Chrysler Imperial,Chrysler Imperial

In [74]:
mtcars[mtcars['mpg_level'] == 'High' ]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,car_name,model
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,Straight,manual,4,1,High,Fiat 128,Fiat 128
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,Straight,manual,4,2,High,Honda Civic,Honda Civic
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,Straight,manual,4,1,High,Toyota Corolla,Toyota Corolla
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,Straight,manual,5,2,High,Lotus Europa,Lotus Europa

In [75]:
mtcars.query("mpg < 23")

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_level,car_name,model
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,Vshaped,manual,4,4,Medium,Mazda RX4,Mazda RX4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,Vshaped,manual,4,4,Medium,Mazda RX4 Wag,Mazda RX4 Wag
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,Straight,manual,4,1,Medium,Datsun 710,Datsun 710
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,Straight,auto,3,1,Medium,Hornet 4 Drive,Hornet 4 Drive
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,Vshaped,auto,3,2,Medium,Hornet Sportabout,Hornet Sportabout
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,Straight,auto,3,1,Medium,Valiant,Valiant
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,Vshaped,auto,3,4,Low,Duster 360,Duster 360
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,Straight,auto,4,2,Medium,Merc 230,Merc 230
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,Straight,auto,4,4,Medium,Merc 280,Merc 280
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,Straight,auto,4,4,Medium,Merc 280C,Merc 280C
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,Vshaped,auto,3,3,Low,Merc 450SE,Merc 450SE
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,Vshaped,auto,3,3,Medium,Merc 450SL,Merc 450SL
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,Vshaped,auto,3,3,Low,Merc 450SLC,Merc 450SLC
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,Vshaped,auto,3,4,Low,Cadillac Fleetwood,Cadillac Fleetwood
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,Vshaped,auto,3,4,Low,Lincoln Continental,Lincoln Continental
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,Vshaped,auto,3,4,Low,Chrysler Imperial,Chrysler Imperial
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,Straight,auto,3,1,Medium,Toyota Corona,Toyota Corona
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,Vshaped,auto,3,2,Low,Dodge Challenger,Dodge Challenger
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,Vshaped,auto,3,2,Low,AMC Javelin,AMC Javelin
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,Vshaped,auto,3,4,Low,Camaro Z28,Camaro Z28
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,Vshaped,auto,3,2,Medium,Pontiac Firebird,Pontiac Firebird
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,Vshaped,manual,5,4,Low,Ford Pantera L,Ford Pantera L
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,Vshaped,manual,5,6,Medium,Ferrari Dino,Ferrari Dino
Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,Vshaped,manual,5,8,Low,Maserati Bora,Maserati Bora
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,Straight,manual,4,2,Medium,Volvo 142E,Volvo 142E

In [12]:
mtcars.filter(items = ['mpg','hp'])

                      mpg   hp
Mazda RX4            21.0  110
Mazda RX4 Wag        21.0  110
Datsun 710           22.8   93
Hornet 4 Drive       21.4  110
Hornet Sportabout    18.7  175
Valiant              18.1  105
Duster 360           14.3  245
Merc 240D            24.4   62
Merc 230             22.8   95
Merc 280             19.2  123
Merc 280C            17.8  123
Merc 450SE           16.4  180
Merc 450SL           17.3  180
Merc 450SLC          15.2  180
Cadillac Fleetwood   10.4  205
Lincoln Continental  10.4  215
Chrysler Imperial    14.7  230
Fiat 128             32.4   66
Honda Civic          30.4   52
Toyota Corolla       33.9   65
Toyota Corona        21.5   97
Dodge Challenger     15.5  150
AMC Javelin          15.2  150
Camaro Z28           13.3  245
Pontiac Firebird     19.2  175
Fiat X1-9            27.3   66
Porsche 914-2        26.0   91
Lotus Europa         30.4  113
Ford Pantera L       15.8  264
Ferrari Dino         19.7  175
Maserati Bora        15.0  335
Volvo 142E           21.4  109

In [13]:
mtcars[mtcars['am'] == 'auto']

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,auto,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,auto,3,4
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,auto,4,2
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,auto,4,2
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,auto,4,4
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,auto,4,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,auto,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,auto,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,auto,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,auto,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,auto,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,auto,3,4
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,auto,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,auto,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,auto,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,auto,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,auto,3,2

In [15]:
mtcars[(mtcars['am'] == 'auto') & (mtcars['cyl'] != '5') & (mtcars['mpg'] > 22 )]
# <> 5, mpg>22

            mpg cyl   disp  hp  drat    wt  qsec vs    am gear carb
Merc 240D  24.4   4  146.7  62  3.69  3.19  20.0  1  auto    4    2
Merc 230   22.8   4  140.8  95  3.92  3.15  22.9  1  auto    4    2

In [16]:
mtcars[mtcars['mpg'].between(left=23, right=26.1, inclusive='left')]
#between condition 23-26.1
#inclusive {both, neither, left, right}

                mpg cyl   disp  hp  drat    wt  qsec vs      am gear carb
Merc 240D      24.4   4  146.7  62  3.69  3.19  20.0  1    auto    4    2
Porsche 914-2  26.0   4  120.3  91  4.43  2.14  16.7  0  manual    5    2

In [17]:
mtcars[mtcars['mpg'].between(23, 30, inclusive= 'neither')]

                mpg cyl   disp  hp  drat     wt  qsec vs      am gear carb
Merc 240D      24.4   4  146.7  62  3.69  3.190  20.0  1    auto    4    2
Fiat X1-9      27.3   4   79.0  66  4.08  1.935  18.9  1  manual    4    1
Porsche 914-2  26.0   4  120.3  91  4.43  2.140  16.7  0  manual    5    2

In [18]:
mtcars[mtcars['gear'].isin ([4,5])]
#look for data within 4,5 values in gear

                 mpg cyl   disp   hp  drat     wt   qsec vs      am gear carb
Mazda RX4       21.0   6  160.0  110  3.90  2.620  16.46  0  manual    4    4
Mazda RX4 Wag   21.0   6  160.0  110  3.90  2.875  17.02  0  manual    4    4
Datsun 710      22.8   4  108.0   93  3.85  2.320  18.61  1  manual    4    1
Merc 240D       24.4   4  146.7   62  3.69  3.190  20.00  1    auto    4    2
Merc 230        22.8   4  140.8   95  3.92  3.150  22.90  1    auto    4    2
Merc 280        19.2   6  167.6  123  3.92  3.440  18.30  1    auto    4    4
Merc 280C       17.8   6  167.6  123  3.92  3.440  18.90  1    auto    4    4
Fiat 128        32.4   4   78.7   66  4.08  2.200  19.47  1  manual    4    1
Honda Civic     30.4   4   75.7   52  4.93  1.615  18.52  1  manual    4    2
Toyota Corolla  33.9   4   71.1   65  4.22  1.835  19.90  1  manual    4    1
Fiat X1-9       27.3   4   79.0   66  4.08  1.935  18.90  1  manual    4    1
Porsche 914-2   26.0   4  120.3   91  4.43  2.140  16.70  0  manual    5    2
Lotus Europa    30.4   4   95.1  113  3.77  1.513  16.90  1  manual    5    2
Ford Pantera L  15.8   8  351.0  264  4.22  3.170  14.50  0  manual    5    4
Ferrari Dino    19.7   6  145.0  175  3.62  2.770  15.50  0  manual    5    6
Maserati Bora   15.0   8  301.0  335  3.54  3.570  14.60  0  manual    5    8
Volvo 142E      21.4   4  121.0  109  4.11  2.780  18.60  1  manual    4    2

In [20]:
mtcars[mtcars['cyl'].isin ([4,6])]
#Cyl value including 4,6

                 mpg cyl   disp   hp  drat     wt   qsec vs      am gear carb
Mazda RX4       21.0   6  160.0  110  3.90  2.620  16.46  0  manual    4    4
Mazda RX4 Wag   21.0   6  160.0  110  3.90  2.875  17.02  0  manual    4    4
Datsun 710      22.8   4  108.0   93  3.85  2.320  18.61  1  manual    4    1
Hornet 4 Drive  21.4   6  258.0  110  3.08  3.215  19.44  1    auto    3    1
Valiant         18.1   6  225.0  105  2.76  3.460  20.22  1    auto    3    1
Merc 240D       24.4   4  146.7   62  3.69  3.190  20.00  1    auto    4    2
Merc 230        22.8   4  140.8   95  3.92  3.150  22.90  1    auto    4    2
Merc 280        19.2   6  167.6  123  3.92  3.440  18.30  1    auto    4    4
Merc 280C       17.8   6  167.6  123  3.92  3.440  18.90  1    auto    4    4
Fiat 128        32.4   4   78.7   66  4.08  2.200  19.47  1  manual    4    1
Honda Civic     30.4   4   75.7   52  4.93  1.615  18.52  1  manual    4    2
Toyota Corolla  33.9   4   71.1   65  4.22  1.835  19.90  1  manual    4    1
Toyota Corona   21.5   4  120.1   97  3.70  2.465  20.01  1    auto    3    1
Fiat X1-9       27.3   4   79.0   66  4.08  1.935  18.90  1  manual    4    1
Porsche 914-2   26.0   4  120.3   91  4.43  2.140  16.70  0  manual    5    2
Lotus Europa    30.4   4   95.1  113  3.77  1.513  16.90  1  manual    5    2
Ferrari Dino    19.7   6  145.0  175  3.62  2.770  15.50  0  manual    5    6
Volvo 142E      21.4   4  121.0  109  4.11  2.780  18.60  1  manual    4    2

In [25]:
mtcars[ (mtcars['gear'].isin([4,5])) & (mtcars['am'] == 'auto')]
# two different condition with different data values using & AND

            mpg cyl   disp   hp  drat    wt  qsec vs    am gear carb
Merc 240D  24.4   4  146.7   62  3.69  3.19  20.0  1  auto    4    2
Merc 230   22.8   4  140.8   95  3.92  3.15  22.9  1  auto    4    2
Merc 280   19.2   6  167.6  123  3.92  3.44  18.3  1  auto    4    4
Merc 280C  17.8   6  167.6  123  3.92  3.44  18.9  1  auto    4    4

In [26]:
mtcars[~mtcars['gear'].isin([4,5])]

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,auto,3,1
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,auto,3,4
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,auto,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,auto,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,auto,3,3
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,auto,3,4
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,auto,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,auto,3,4
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,auto,3,1
Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,auto,3,2
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,auto,3,2
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,auto,3,4
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,auto,3,2

# Select dtypes

In [27]:
mtcars.dtypes

mpg      float64
cyl     category
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs      category
am      category
gear    category
carb    category
dtype: object

In [28]:
mtcars.select_dtypes(include='number')

                      mpg   disp   hp  drat     wt   qsec
Mazda RX4            21.0  160.0  110  3.90  2.620  16.46
Mazda RX4 Wag        21.0  160.0  110  3.90  2.875  17.02
Datsun 710           22.8  108.0   93  3.85  2.320  18.61
Hornet 4 Drive       21.4  258.0  110  3.08  3.215  19.44
Hornet Sportabout    18.7  360.0  175  3.15  3.440  17.02
Valiant              18.1  225.0  105  2.76  3.460  20.22
Duster 360           14.3  360.0  245  3.21  3.570  15.84
Merc 240D            24.4  146.7   62  3.69  3.190  20.00
Merc 230             22.8  140.8   95  3.92  3.150  22.90
Merc 280             19.2  167.6  123  3.92  3.440  18.30
Merc 280C            17.8  167.6  123  3.92  3.440  18.90
Merc 450SE           16.4  275.8  180  3.07  4.070  17.40
Merc 450SL           17.3  275.8  180  3.07  3.730  17.60
Merc 450SLC          15.2  275.8  180  3.07  3.780  18.00
Cadillac Fleetwood   10.4  472.0  205  2.93  5.250  17.98
Lincoln Continental  10.4  460.0  215  3.00  5.424  17.82
Chrysler Imperial    14.7  440.0  230  3.23  5.345  17.42
Fiat 128             32.4   78.7   66  4.08  2.200  19.47
Honda Civic          30.4   75.7   52  4.93  1.615  18.52
Toyota Corolla       33.9   71.1   65  4.22  1.835  19.90
Toyota Corona        21.5  120.1   97  3.70  2.465  20.01
Dodge Challenger     15.5  318.0  150  2.76  3.520  16.87
AMC Javelin          15.2  304.0  150  3.15  3.435  17.30
Camaro Z28           13.3  350.0  245  3.73  3.840  15.41
Pontiac Firebird     19.2  400.0  175  3.08  3.845  17.05
Fiat X1-9            27.3   79.0   66  4.08  1.935  18.90
Porsche 914-2        26.0  120.3   91  4.43  2.140  16.70
Lotus Europa         30.4   95.1  113  3.77  1.513  16.90
Ford Pantera L       15.8  351.0  264  4.22  3.170  14.50
Ferrari Dino         19.7  145.0  175  3.62  2.770  15.50
Maserati Bora        15.0  301.0  335  3.54  3.570  14.60
Volvo 142E           21.4  121.0  109  4.11  2.780  18.60

In [31]:
mtcars.select_dtypes(include='category').head()

                  cyl vs      am gear carb
Mazda RX4           6  0  manual    4    4
Mazda RX4 Wag       6  0  manual    4    4
Datsun 710          4  1  manual    4    1
Hornet 4 Drive      6  1    auto    3    1
Hornet Sportabout   8  0    auto    3    2

In [32]:
mtcars.select_dtypes(include='object').head()

Empty DataFrame
Columns: []
Index: [Mazda RX4, Mazda RX4 Wag, Datsun 710, Hornet 4 Drive, Hornet Sportabout]

# nlargest for a column

In [35]:
mtcars.nlargest(5, 'mpg')
#condition above 5mpg

                 mpg cyl  disp   hp  drat     wt   qsec vs      am gear carb
Toyota Corolla  33.9   4  71.1   65  4.22  1.835  19.90  1  manual    4    1
Fiat 128        32.4   4  78.7   66  4.08  2.200  19.47  1  manual    4    1
Honda Civic     30.4   4  75.7   52  4.93  1.615  18.52  1  manual    4    2
Lotus Europa    30.4   4  95.1  113  3.77  1.513  16.90  1  manual    5    2
Fiat X1-9       27.3   4  79.0   66  4.08  1.935  18.90  1  manual    4    1

In [37]:
mtcars.nsmallest(5, 'wt')
#condition with below 5 wt

                 mpg cyl   disp   hp  drat     wt   qsec vs      am gear carb
Lotus Europa    30.4   4   95.1  113  3.77  1.513  16.90  1  manual    5    2
Honda Civic     30.4   4   75.7   52  4.93  1.615  18.52  1  manual    4    2
Toyota Corolla  33.9   4   71.1   65  4.22  1.835  19.90  1  manual    4    1
Fiat X1-9       27.3   4   79.0   66  4.08  1.935  18.90  1  manual    4    1
Porsche 914-2   26.0   4  120.3   91  4.43  2.140  16.70  0  manual    5    2

# sort values

In [53]:
mtcars=mtcars.sort_values(by='mpg', ascending=True, inplace=False) 
#check this line to 53

In [52]:
mtcars.sort_values(by='mpg', ascending=True, inplace=True).head()

AttributeError: 'NoneType' object has no attribute 'head'

In [54]:
mtcars.sort_values(['gear','mpg']).head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,auto,3,4
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,auto,3,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,auto,3,4
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,auto,3,4
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,auto,3,4

In [55]:
mtcars.sort_values(['gear','mpg'], ascending=[False,True]).head()

                 mpg cyl   disp   hp  drat     wt  qsec vs      am gear carb
Maserati Bora   15.0   8  301.0  335  3.54  3.570  14.6  0  manual    5    8
Ford Pantera L  15.8   8  351.0  264  4.22  3.170  14.5  0  manual    5    4
Ferrari Dino    19.7   6  145.0  175  3.62  2.770  15.5  0  manual    5    6
Porsche 914-2   26.0   4  120.3   91  4.43  2.140  16.7  0  manual    5    2
Lotus Europa    30.4   4   95.1  113  3.77  1.513  16.9  1  manual    5    2

# Apr 12

In [58]:
import pandas as pd
import numpy as np
from pydataset import data
mtcars = data('mtcars')
mtcars.shape

(32, 11)

In [59]:
mtcars.pivot_table(values = 'mpg', index='gear', observed=False)

            mpg
gear
3     16.106667
4     24.533333
5     21.380000

In [60]:
mtcars.pivot_table(values = 'hp', index='cyl', observed=False)

             hp
cyl
4     82.636364
6    122.285714
8    209.214286

In [62]:
pd.pivot_table( data=mtcars, observed=False,
              index='gear',
              values='mpg',
              aggfunc='median'
)

       mpg
gear
3     15.5
4     22.8
5     19.7

In [64]:
pivot1 = pd.pivot_table(
    data=mtcars, observed=False,
    index='gear',
    columns='am',
    values='mpg',
    aggfunc='mean'
)

In [65]:
pivot1

am            0       1
gear
3     16.106667     NaN
4     21.050000  26.275
5           NaN  21.380

In [66]:
mtcars.am.value_counts()
mtcars.cyl.value_counts()

cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [67]:
pd.pivot_table ( observed=False, data=mtcars, index='gear', columns='am', values='mpg', \
               aggfunc=['mean', 'max', 'min', 'count', 'sum'] ).reset_index()

   gear       mean           max         min       count         sum
am               0       1     0     1     0     1     0    1      0      1
0     3  16.106667     NaN  21.5   NaN  10.4   NaN  15.0  NaN  241.6    NaN
1     4  21.050000  26.275  24.4  33.9  17.8  21.0   4.0  8.0   84.2  210.2
2     5        NaN  21.380   NaN  30.4   NaN  15.0   NaN  5.0    NaN  106.9

In [71]:
pd.pivot_table(dat= mtcars, index=['gear','am'], columns='cyl', values='mpg', \
              aggfucn=['mean', 'max', 'min' , 'count', 'sum', 'std'] ).reset_index()

TypeError: pivot_table() got an unexpected keyword argument 'dat'. Did you mean 'data'?

In [72]:
pd.pivot_table(data=mtcars, index='cyl', columns='carb', values='hp', aggfunc=['min','max','count'])

        min                                       max                       \
carb      1      2      3      4      6      8      1      2      3      4
cyl
4      65.0   52.0    NaN    NaN    NaN    NaN   97.0  113.0    NaN    NaN
6     105.0    NaN    NaN  110.0  175.0    NaN  110.0    NaN    NaN  123.0
8       NaN  150.0  180.0  205.0    NaN  335.0    NaN  175.0  180.0  264.0

                   count
carb      6      8     1    2    3    4    6    8
cyl
4       NaN    NaN   5.0  6.0  NaN  NaN  NaN  NaN
6     175.0    NaN   2.0  NaN  NaN  4.0  1.0  NaN
8       NaN  335.0   NaN  4.0  3.0  6.0  NaN  1.0


# Practice with Student Data

In [76]:
sheet_id = '1ABCDefGhIJklMNopQRstuVWxyz12345678'
gid1 = '132995188'
gid2 = '330609257'

In [74]:
url1 = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"
print(url1)

NameError: name 'gid' is not defined