# SQL Python connect

In [18]:
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [19]:
engine1 = create_engine("mysql+pymysql://root:piit2025@localhost:3306/piit")
engine1

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [20]:
# function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [21]:
q('show tables')

  Tables_in_piit
0           dept
1            emp
2       students

In [22]:
q('show tables')

  Tables_in_piit
0           dept
1            emp
2       students

In [23]:
q('select * from dept')

   deptno       dname       loc
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [24]:
q('show tables')

  Tables_in_piit
0           dept
1            emp
2       students

In [25]:
q("SELECT * FROM emp")

    empno   ename        job     mgr    hiredate     sal    comm  deptno
0    1234  DHIRAJ    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
1    1235  KHULAN    ANALYST  7839.0  1990-12-17  6000.0   100.0      20
2    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
3    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
4    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
5    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
6    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
7    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
8    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
9    7788   SCOTT    ANALYST  7566.0  1987-04-19  3000.0     NaN      20
10   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
11   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
12   7876   ADAMS      CLERK  7788.0  1987-05-23  1100.0     NaN      20
13   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
14   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
15   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [26]:
q("select max(sal) from emp")

   max(sal)
0    6000.0

In [27]:
query = 'select * from emp'
emp = pd.read_sql(query, engine1)
emp

    empno   ename        job     mgr    hiredate     sal    comm  deptno
0    1234  DHIRAJ    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
1    1235  KHULAN    ANALYST  7839.0  1990-12-17  6000.0   100.0      20
2    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
3    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
4    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
5    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
6    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
7    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
8    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
9    7788   SCOTT    ANALYST  7566.0  1987-04-19  3000.0     NaN      20
10   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
11   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
12   7876   ADAMS      CLERK  7788.0  1987-05-23  1100.0     NaN      20
13   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
14   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
15   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [28]:
emp = q('select * from emp')
emp.head()

   empno   ename       job     mgr    hiredate     sal   comm  deptno
0   1234  DHIRAJ   ANALYST  7839.0  1988-12-17  5000.0  100.0      10
1   1235  KHULAN   ANALYST  7839.0  1990-12-17  6000.0  100.0      20
2   7369   SMITH     CLERK  7902.0  1980-12-17   800.0    NaN      20
3   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0      30
4   7521    WARD  SALESMAN  7698.0  1981-02-22  1250.0  500.0      30

In [29]:
dept = q('select * from dept')
dept.head()

   deptno       dname       loc
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [32]:
#Combine & merge the column
empdept= pd.merge(emp, dept, on='deptno', how='inner')
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK
1,1235,KHULAN,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,RESEARCH,DALLAS
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO

In [33]:
empdept.groupby(['dname','job']).size().reset_index()

        dname        job  0
0  ACCOUNTING    ANALYST  1
1  ACCOUNTING      CLERK  1
2  ACCOUNTING    MANAGER  1
3  ACCOUNTING  PRESIDENT  1
4    RESEARCH    ANALYST  3
5    RESEARCH      CLERK  2
6    RESEARCH    MANAGER  1
7       SALES      CLERK  1
8       SALES    MANAGER  1
9       SALES   SALESMAN  4

In [34]:
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK
1,1235,KHULAN,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,RESEARCH,DALLAS
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO

In [21]:
empdept.groupby('dname').size()

dname
ACCOUNTING    4
RESEARCH      6
SALES         6
dtype: int64

In [24]:
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK
1,1235,KHULAN,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,RESEARCH,DALLAS
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO

In [26]:
empdept.shape

(16, 10)

empdept.dtypes

empdept.dtypes

In [27]:
empdept.info

<bound method DataFrame.info of     empno   ename        job     mgr    hiredate     sal    comm  deptno  \
0    1234  DHIRAJ    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
1    1235  KHULAN    ANALYST  7839.0  1990-12-17  6000.0   100.0      20
2    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
3    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
4    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
5    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
6    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
7    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
8    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
9    7788   SCOTT    ANALYST  7566.0  1987-04-19  3000.0     NaN      20
10   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
11   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
12   7876   ADAMS      CLERK  7788.0  1987-05-23  1100.0     NaN      20
13   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
14   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
15   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

         dname       loc
0   ACCOUNTING  NEW YORK
1     RESEARCH    DALLAS
2     RESEARCH    DALLAS
3        SALES   CHICAGO
4        SALES   CHICAGO
5     RESEARCH    DALLAS
6        SALES   CHICAGO
7        SALES   CHICAGO
8   ACCOUNTING  NEW YORK
9     RESEARCH    DALLAS
10  ACCOUNTING  NEW YORK
11       SALES   CHICAGO
12    RESEARCH    DALLAS
13       SALES   CHICAGO
14    RESEARCH    DALLAS
15  ACCOUNTING  NEW YORK  >

In [28]:
empdept.describe

<bound method NDFrame.describe of     empno   ename        job     mgr    hiredate     sal    comm  deptno  \
0    1234  DHIRAJ    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
1    1235  KHULAN    ANALYST  7839.0  1990-12-17  6000.0   100.0      20
2    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
3    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
4    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
5    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
6    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
7    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
8    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
9    7788   SCOTT    ANALYST  7566.0  1987-04-19  3000.0     NaN      20
10   7839    KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
11   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
12   7876   ADAMS      CLERK  7788.0  1987-05-23  1100.0     NaN      20
13   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
14   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
15   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

         dname       loc
0   ACCOUNTING  NEW YORK
1     RESEARCH    DALLAS
2     RESEARCH    DALLAS
3        SALES   CHICAGO
4        SALES   CHICAGO
5     RESEARCH    DALLAS
6        SALES   CHICAGO
7        SALES   CHICAGO
8   ACCOUNTING  NEW YORK
9     RESEARCH    DALLAS
10  ACCOUNTING  NEW YORK
11       SALES   CHICAGO
12    RESEARCH    DALLAS
13       SALES   CHICAGO
14    RESEARCH    DALLAS
15  ACCOUNTING  NEW YORK  >

In [29]:
empdept.dtypes

empno         int64
ename        object
job          object
mgr         float64
hiredate     object
sal         float64
comm        float64
deptno        int64
dname        object
loc          object
dtype: object

In [31]:
empdept.isnull().sum()

empno        0
ename        0
job          0
mgr          1
hiredate     0
sal          0
comm        10
deptno       0
dname        0
loc          0
dtype: int64

In [35]:
import datetime as dt

In [37]:
empdept['hiredate'] = pd.to_datetime(empdept['hiredate']) #.dt.date

In [38]:
empdept.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   empno     16 non-null     int64
 1   ename     16 non-null     object
 2   job       16 non-null     object
 3   mgr       15 non-null     float64
 4   hiredate  16 non-null     datetime64[ns]
 5   sal       16 non-null     float64
 6   comm      6 non-null      float64
 7   deptno    16 non-null     int64
 8   dname     16 non-null     object
 9   loc       16 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 1.4+ KB

In [39]:
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK
1,1235,KHULAN,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,RESEARCH,DALLAS
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO

In [40]:
empdept['hireyear'] = empdept['hiredate'].dt.year
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK,1988
1,1235,KHULAN,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,RESEARCH,DALLAS,1990
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS,1980
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO,1981
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO,1981

In [41]:
empdept[(empdept['hireyear'] >= 1982) & (empdept['dname'] == 'RESEARCH')]

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
1,1235,KHULAN,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,RESEARCH,DALLAS,1990
9,7788,SCOTT,ANALYST,7566.0,1987-04-19,3000.0,NaN,20,RESEARCH,DALLAS,1987
12,7876,ADAMS,CLERK,7788.0,1987-05-23,1100.0,NaN,20,RESEARCH,DALLAS,1987

In [42]:
today = pd.to_datetime('today')
today

Timestamp('2026-05-13 15:31:56.307948')

In [43]:
import numpy as np

In [45]:
empdept['monthServed'] = ((today - empdept['hiredate']) / np.timedelta64(1, 'D')/ 30.44).astype(int)
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear,monthServed
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK,1988,448
1,1235,KHULAN,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,RESEARCH,DALLAS,1990,424
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,NaN,20,RESEARCH,DALLAS,1980,544
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO,1981,542
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO,1981,542

In [53]:
print(empdept.columns.tolist())

['empno', 'ename', 'job', 'mgr', 'hiredate', 'sal', 'comm', 'deptno', 'dname', 'loc', 'hireyear', 'monthServed']

In [61]:
empdept.drop(columns='months_diff', inplace=True, errors='ignore')
empdept

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc,hireyear
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK,1988
1,1235,KHULAN,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,RESEARCH,DALLAS,1990
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,0.0,20,RESEARCH,DALLAS,1980
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO,1981
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO,1981
5,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,0.0,20,RESEARCH,DALLAS,1981
6,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,CHICAGO,1981
7,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,0.0,30,SALES,CHICAGO,1981
8,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,0.0,10,ACCOUNTING,NEW YORK,1981
9,7788,SCOTT,ANALYST,7566.0,1987-04-19,3000.0,0.0,20,RESEARCH,DALLAS,1987
10,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,0.0,10,ACCOUNTING,NEW YORK,1981
11,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,CHICAGO,1981
12,7876,ADAMS,CLERK,7788.0,1987-05-23,1100.0,0.0,20,RESEARCH,DALLAS,1987
13,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,0.0,30,SALES,CHICAGO,1981
14,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,0.0,20,RESEARCH,DALLAS,1981
15,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,0.0,10,ACCOUNTING,NEW YORK,1982

In [64]:
#dropping "loc" columns
empdept.drop(columns='loc', inplace=True)
empdept

KeyError: "['loc'] not found in axis"

In [67]:
empdept['comm'] = empdept['comm'].fillna(0)

# Salary analysis

In [65]:
empdept['sal'].mean()

np.float64(2501.5625)

In [35]:
empdept['sal'].min()

800.0

In [36]:
empdept['sal'].sum()

np.float64(40025.0)

In [37]:
empdept['sal'].max()

6000.0

In [39]:
empdept['sal'].median()

2025.0

In [40]:
empdept['sal'].std()

1617.159772306579

In [44]:
empdept.groupby('job')['sal'].mean()

job
ANALYST      4250.000000
CLERK        1037.500000
MANAGER      2758.333333
PRESIDENT    5000.000000
SALESMAN     1400.000000
Name: sal, dtype: float64

In [45]:
empdept.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,loc
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,NEW YORK
1,1235,KHULAN,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,RESEARCH,DALLAS
2,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,0.0,20,RESEARCH,DALLAS
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,CHICAGO
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,CHICAGO

In [48]:
empdept.groupby('dname')['sal'].mean()

dname
ACCOUNTING    3437.500000
RESEARCH      2812.500000
SALES         1566.666667
Name: sal, dtype: float64

In [79]:
#filtering location
empdept.groupby('loc').size()

loc
CHICAGO     6
DALLAS      6
NEW YORK    4
dtype: int64

In [49]:
empdept.groupby('dname')['sal'].agg(['mean','max','count'])

                   mean     max  count
dname
ACCOUNTING  3437.500000  5000.0      4
RESEARCH    2812.500000  6000.0      6
SALES       1566.666667  2850.0      6

In [86]:
empdept['hiredate'] = pd.to_datetime(empdept['hiredate'])
filtered = empdept[empdept['hiredate'] > '1981-01-01']

In [81]:
filtered.groupby(filtered['hiredate'].dt.year).size()
filtered.groupby(filtered['hiredate'].dt.year)['sal'].mean()

hiredate
1981    2282.5
1982    1300.0
1987    2050.0
1988    5000.0
1990    6000.0
Name: sal, dtype: float64

In [50]:
empdept.groupby('ename')['sal'].agg(['mean','max','count'])

          mean     max  count
ename
ADAMS   1100.0  1100.0      1
ALLEN   1600.0  1600.0      1
BLAKE   2850.0  2850.0      1
CLARK   2450.0  2450.0      1
DHIRAJ  5000.0  5000.0      1
FORD    3000.0  3000.0      1
JAMES    950.0   950.0      1
JONES   2975.0  2975.0      1
KHULAN  6000.0  6000.0      1
KING    5000.0  5000.0      1
MARTIN  1250.0  1250.0      1
MILLER  1300.0  1300.0      1
SCOTT   3000.0  3000.0      1
SMITH    800.0   800.0      1
TURNER  1500.0  1500.0      1
WARD    1250.0  1250.0      1

In [51]:
empdept.groupby('dname').size()

dname
ACCOUNTING    4
RESEARCH      6
SALES         6
dtype: int64

In [52]:
empdept.groupby('dname').count()

            empno  ename  job  mgr  hiredate  sal  comm  deptno  loc
dname
ACCOUNTING      4      4    4    3         4    4     4       4    4
RESEARCH        6      6    6    6         6    6     6       6    6
SALES           6      6    6    6         6    6     6       6    6

In [56]:
# Total compensation sal+comm
empdept['total_comp'] = empdept['sal'] + empdept['comm']
empdept[['ename','sal','comm','total_comp']].sort_values('total_comp', ascending=False)

     ename     sal    comm  total_comp
1   KHULAN  6000.0   100.0      6100.0
0   DHIRAJ  5000.0   100.0      5100.0
10    KING  5000.0     0.0      5000.0
9    SCOTT  3000.0     0.0      3000.0
14    FORD  3000.0     0.0      3000.0
5    JONES  2975.0     0.0      2975.0
7    BLAKE  2850.0     0.0      2850.0
6   MARTIN  1250.0  1400.0      2650.0
8    CLARK  2450.0     0.0      2450.0
3    ALLEN  1600.0   300.0      1900.0
4     WARD  1250.0   500.0      1750.0
11  TURNER  1500.0     0.0      1500.0
15  MILLER  1300.0     0.0      1300.0
12   ADAMS  1100.0     0.0      1100.0
13   JAMES   950.0     0.0       950.0
2    SMITH   800.0     0.0       800.0

In [61]:
# Sequencing order number
result = empdept[['ename','sal','comm','total_comp']]\
         .sort_values('total_comp', ascending=False)\
         .reset_index(drop=True)

result.index += 1  # start from 1 instead of 0
result

     ename     sal    comm  total_comp
1   KHULAN  6000.0   100.0      6100.0
2   DHIRAJ  5000.0   100.0      5100.0
3     KING  5000.0     0.0      5000.0
4    SCOTT  3000.0     0.0      3000.0
5     FORD  3000.0     0.0      3000.0
6    JONES  2975.0     0.0      2975.0
7    BLAKE  2850.0     0.0      2850.0
8   MARTIN  1250.0  1400.0      2650.0
9    CLARK  2450.0     0.0      2450.0
10   ALLEN  1600.0   300.0      1900.0
11    WARD  1250.0   500.0      1750.0
12  TURNER  1500.0     0.0      1500.0
13  MILLER  1300.0     0.0      1300.0
14   ADAMS  1100.0     0.0      1100.0
15   JAMES   950.0     0.0       950.0
16   SMITH   800.0     0.0       800.0

In [68]:
empdept[empdept['hiredate'] > '1981-01-01']

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,hireyear
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,1988
1,1235,KHULAN,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,RESEARCH,1990
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,1981
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,1981
5,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,0.0,20,RESEARCH,1981
6,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,1981
7,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,0.0,30,SALES,1981
8,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,0.0,10,ACCOUNTING,1981
9,7788,SCOTT,ANALYST,7566.0,1987-04-19,3000.0,0.0,20,RESEARCH,1987
10,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,0.0,10,ACCOUNTING,1981
11,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,1981
12,7876,ADAMS,CLERK,7788.0,1987-05-23,1100.0,0.0,20,RESEARCH,1987
13,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,0.0,30,SALES,1981
14,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,0.0,20,RESEARCH,1981
15,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,0.0,10,ACCOUNTING,1982

In [69]:
empdept[empdept['hiredate'] > '1981-01-01'].sort_values('hiredate')

,empno,ename,job,mgr,hiredate,sal,comm,deptno,dname,hireyear
3,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30,SALES,1981
4,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30,SALES,1981
5,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,0.0,20,RESEARCH,1981
7,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,0.0,30,SALES,1981
8,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,0.0,10,ACCOUNTING,1981
11,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30,SALES,1981
6,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30,SALES,1981
10,7839,KING,PRESIDENT,NaN,1981-11-17,5000.0,0.0,10,ACCOUNTING,1981
13,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,0.0,30,SALES,1981
14,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,0.0,20,RESEARCH,1981
15,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,0.0,10,ACCOUNTING,1982
9,7788,SCOTT,ANALYST,7566.0,1987-04-19,3000.0,0.0,20,RESEARCH,1987
12,7876,ADAMS,CLERK,7788.0,1987-05-23,1100.0,0.0,20,RESEARCH,1987
0,1234,DHIRAJ,ANALYST,7839.0,1988-12-17,5000.0,100.0,10,ACCOUNTING,1988
1,1235,KHULAN,ANALYST,7839.0,1990-12-17,6000.0,100.0,20,RESEARCH,1990

In [70]:
empdept['hireyear'].value_counts().sort_index()

hireyear
1980     1
1981    10
1982     1
1987     2
1988     1
1990     1
Name: count, dtype: int64