# Pandas

In [1]:
import pandas as pd #pd is an alias for pandas

In [ ]:
#pd

In [3]:
pip install pydataset

Collecting pydataset
  Downloading pydataset-0.2.0.tar.gz (15.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 6.3 MB/s  0:00:02 eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (from pydataset) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->pydataset) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->pydataset) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->pydataset) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->pydataset) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->pydataset) (1.17.0)
Building wheels for collected packages: pydataset
  Building wheel for pydataset (pyproject.toml) ... done
  Created wheel for pydataset: filename=pydataset-0.2.0-py3-none-any.whl size=15939220 sha256=a4eb4b808be9a5d90b4c00efa01b76cd4d8983f49fa778754deb5ab3b22e5f1a
  Stored in directory: /Users/huslenhuugiiz/Library/Caches/pip/wheels/49/2a/45/180e1199b8d925b5c43df8f9850dcc2e5dfc94e3e99a55b83e
Successfully built pydataset
Installing collected packages: pydataset
Successfully installed pydataset-0.2.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
from pydataset import data #load library of pydataset and import mtcars data from it

initiated datasets repo at: /Users/huslenhuugiiz/.pydataset/

In [5]:
import pandas as pd #pd is an alias for pandas
#pip install pydataset
from pydataset import data #load library of pydataset and import mtcars data from it
#https://pydataset.readthedocs.io/en/latest/
mtcars = data('mtcars')
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [5]:
import pandas as pd

In [6]:
#p

In [7]:
pip install pydataset

Requirement already satisfied: pydataset in /opt/anaconda3/lib/python3.13/site-packages (0.2.0)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (from pydataset) (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->pydataset) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->pydataset) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->pydataset) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->pydataset) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->pydataset) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
from pydataset import data

In [10]:
import pandas as pd #pd is an alias for pandas
#pip install pydataset
from pydataset import data #load library of pydataset and import mtcars data from it
#https://pydataset.readthedocs.io/en/latest/
mtcars = data('mtcars')
mtcars.head(3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [11]:
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [12]:
mtcars.head(2)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

In [13]:
pd.set_option('display.max_columns', None)   # Show all columns
pd.set_option('display.width', 100)          # Set line width before wrapping
pd.set_option('display.max_colwidth', None)

In [15]:
from pydataset import data 
mtcars = data('mtcars')
mtcars.head(4)

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710      22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1

In [16]:
mtcars[0:10:3]

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Duster 360      14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
Merc 280        19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4

In [17]:
type(mtcars)

pandas.core.frame.DataFrame

In [18]:
mtcars.head(n=3)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [23]:
type(mtcars)

pandas.core.frame.DataFrame

In [24]:
mtcars.head()

                    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [25]:
mtcars.tail(4) #last 4 rows will shown as a result

                 mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
Ford Pantera L  15.8    8  351.0  264  4.22  3.17  14.5   0   1     5     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.77  15.5   0   1     5     6
Maserati Bora   15.0    8  301.0  335  3.54  3.57  14.6   0   1     5     8
Volvo 142E      21.4    4  121.0  109  4.11  2.78  18.6   1   1     4     2

In [27]:
mtcars.sample(3) #Random rows will shown as a sample

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Merc 240D      24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4

In [28]:
mtcars.shape

(32, 11)

In [29]:
mtcars.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb'], dtype='object')

In [33]:
mtcars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Mazda RX4 to Volvo 142E
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64
 8   am      32 non-null     int64
 9   gear    32 non-null     int64
 10  carb    32 non-null     int64
dtypes: float64(5), int64(6)
memory usage: 3.0+ KB

In [34]:
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [35]:
mtcars.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive', 'Hornet Sportabout',
       'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230', 'Merc 280', 'Merc 280C', 'Merc 450SE',
       'Merc 450SL', 'Merc 450SLC', 'Cadillac Fleetwood', 'Lincoln Continental',
       'Chrysler Imperial', 'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird', 'Fiat X1-9',
       'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L', 'Ferrari Dino', 'Maserati Bora',
       'Volvo 142E'],
      dtype='object')

In [36]:
mtcars.head(2)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

# Summary

In [37]:
mtcars.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [39]:
mtcars.mpg.describe()

count    32.000000
mean     20.090625
std       6.026948
min      10.400000
25%      15.425000
50%      19.200000
75%      22.800000
max      33.900000
Name: mpg, dtype: float64

In [40]:
mtcars.cyl.describe()

count    32.000000
mean      6.187500
std       1.785922
min       4.000000
25%       4.000000
50%       6.000000
75%       8.000000
max       8.000000
Name: cyl, dtype: float64

In [41]:
mtcars.describe(include='all')

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [42]:
mtcars.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [46]:
mtcars

                      mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4            21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag        21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710           22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive       21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
Valiant              18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
Duster 360           14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
Merc 240D            24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
Merc 230             22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
Merc 280             19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
Merc 280C            17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
Merc 450SE           16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
Merc 450SL           17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
Merc 450SLC          15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
Fiat 128             32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
Honda Civic          30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
Toyota Corolla       33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
Toyota Corona        21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
Dodge Challenger     15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
AMC Javelin          15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
Camaro Z28           13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
Fiat X1-9            27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
Porsche 914-2        26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
Lotus Europa         30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
Ford Pantera L       15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
Ferrari Dino         19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
Maserati Bora        15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
Volvo 142E           21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [48]:
mtcars.cyl.value_counts()

cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [49]:
mtcars.hp.value_counts()

hp
110    3
175    3
180    3
245    2
123    2
150    2
66     2
65     1
335    1
264    1
113    1
91     1
97     1
230    1
52     1
93     1
215    1
205    1
95     1
62     1
105    1
109    1
Name: count, dtype: int64

In [50]:
mtcars.nunique()

mpg     25
cyl      3
disp    27
hp      22
drat    22
wt      29
qsec    30
vs       2
am       2
gear     3
carb     6
dtype: int64

In [51]:
mtcars.gear.value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [53]:
mtcars['am'].value_counts()

am
0    19
1    13
Name: count, dtype: int64

In [54]:
mtcars['carb'].value_counts()

carb
4    10
2    10
1     7
3     3
6     1
8     1
Name: count, dtype: int64

In [58]:
mtcars.to_csv('mtcarsdata.csv', index=False)

In [57]:
mtcars2 = pd.read_csv('mtcarsdata.csv')
mtcars2.head(2)

    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

# Excel generation

In [60]:
mtcars.to_excel('mtcarsdata2.xlsx', index=False)

In [62]:
mtcars3 = pd.read_excel ('mtcarsdata2.xlsx', sheet_name=0)
mtcars3.head(5)

          Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [63]:
mtcars.to_excel('mtcarsdata2.xlsx', index=True)

In [66]:
mtcars3 = pd.read_excel ('mtcarsdata2.xlsx', sheet_name=0)
mtcars3.head(5)

          Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [67]:
mtcars.shape

(32, 11)

In [69]:
mtcars.isnull()

                       mpg    cyl   disp     hp   drat     wt   qsec     vs     am   gear   carb
Mazda RX4            False  False  False  False  False  False  False  False  False  False  False
Mazda RX4 Wag        False  False  False  False  False  False  False  False  False  False  False
Datsun 710           False  False  False  False  False  False  False  False  False  False  False
Hornet 4 Drive       False  False  False  False  False  False  False  False  False  False  False
Hornet Sportabout    False  False  False  False  False  False  False  False  False  False  False
Valiant              False  False  False  False  False  False  False  False  False  False  False
Duster 360           False  False  False  False  False  False  False  False  False  False  False
Merc 240D            False  False  False  False  False  False  False  False  False  False  False
Merc 230             False  False  False  False  False  False  False  False  False  False  False
Merc 280             False  False  False  False  False  False  False  False  False  False  False
Merc 280C            False  False  False  False  False  False  False  False  False  False  False
Merc 450SE           False  False  False  False  False  False  False  False  False  False  False
Merc 450SL           False  False  False  False  False  False  False  False  False  False  False
Merc 450SLC          False  False  False  False  False  False  False  False  False  False  False
Cadillac Fleetwood   False  False  False  False  False  False  False  False  False  False  False
Lincoln Continental  False  False  False  False  False  False  False  False  False  False  False
Chrysler Imperial    False  False  False  False  False  False  False  False  False  False  False
Fiat 128             False  False  False  False  False  False  False  False  False  False  False
Honda Civic          False  False  False  False  False  False  False  False  False  False  False
Toyota Corolla       False  False  False  False  False  False  False  False  False  False  False
Toyota Corona        False  False  False  False  False  False  False  False  False  False  False
Dodge Challenger     False  False  False  False  False  False  False  False  False  False  False
AMC Javelin          False  False  False  False  False  False  False  False  False  False  False
Camaro Z28           False  False  False  False  False  False  False  False  False  False  False
Pontiac Firebird     False  False  False  False  False  False  False  False  False  False  False
Fiat X1-9            False  False  False  False  False  False  False  False  False  False  False
Porsche 914-2        False  False  False  False  False  False  False  False  False  False  False
Lotus Europa         False  False  False  False  False  False  False  False  False  False  False
Ford Pantera L       False  False  False  False  False  False  False  False  False  False  False
Ferrari Dino         False  False  False  False  False  False  False  False  False  False  False
Maserati Bora        False  False  False  False  False  False  False  False  False  False  False
Volvo 142E           False  False  False  False  False  False  False  False  False  False  False

In [72]:
mtcars.isnull().sum().sum() #ask why it has 2 sums

np.int64(0)

In [78]:
mtcars.isnull().head()

                     mpg    cyl   disp     hp   drat     wt   qsec     vs     am   gear   carb
Mazda RX4          False  False  False  False  False  False  False  False  False  False  False
Mazda RX4 Wag      False  False  False  False  False  False  False  False  False  False  False
Datsun 710         False  False  False  False  False  False  False  False  False  False  False
Hornet 4 Drive     False  False  False  False  False  False  False  False  False  False  False
Hornet Sportabout  False  False  False  False  False  False  False  False  False  False  False

In [79]:
mtcars.isnull().sum(axis=0)

mpg     0
cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

In [80]:
mtcars.isnull().sum(axis=1)

Mazda RX4              0
Mazda RX4 Wag          0
Datsun 710             0
Hornet 4 Drive         0
Hornet Sportabout      0
Valiant                0
Duster 360             0
Merc 240D              0
Merc 230               0
Merc 280               0
Merc 280C              0
Merc 450SE             0
Merc 450SL             0
Merc 450SLC            0
Cadillac Fleetwood     0
Lincoln Continental    0
Chrysler Imperial      0
Fiat 128               0
Honda Civic            0
Toyota Corolla         0
Toyota Corona          0
Dodge Challenger       0
AMC Javelin            0
Camaro Z28             0
Pontiac Firebird       0
Fiat X1-9              0
Porsche 914-2          0
Lotus Europa           0
Ford Pantera L         0
Ferrari Dino           0
Maserati Bora          0
Volvo 142E             0
dtype: int64

In [81]:
mtcars.notnull().sum(axis=0)

mpg     32
cyl     32
disp    32
hp      32
drat    32
wt      32
qsec    32
vs      32
am      32
gear    32
carb    32
dtype: int64

In [82]:
mtcars.notnull().sum(axis=1)

Mazda RX4              11
Mazda RX4 Wag          11
Datsun 710             11
Hornet 4 Drive         11
Hornet Sportabout      11
Valiant                11
Duster 360             11
Merc 240D              11
Merc 230               11
Merc 280               11
Merc 280C              11
Merc 450SE             11
Merc 450SL             11
Merc 450SLC            11
Cadillac Fleetwood     11
Lincoln Continental    11
Chrysler Imperial      11
Fiat 128               11
Honda Civic            11
Toyota Corolla         11
Toyota Corona          11
Dodge Challenger       11
AMC Javelin            11
Camaro Z28             11
Pontiac Firebird       11
Fiat X1-9              11
Porsche 914-2          11
Lotus Europa           11
Ford Pantera L         11
Ferrari Dino           11
Maserati Bora          11
Volvo 142E             11
dtype: int64

In [83]:
mtcars.sum(axis=0)

mpg      642.900
cyl      198.000
disp    7383.100
hp      4694.000
drat     115.090
wt       102.952
qsec     571.160
vs        14.000
am        13.000
gear     118.000
carb      90.000
dtype: float64

In [84]:
mtcars.sum(axis=1)

Mazda RX4              328.980
Mazda RX4 Wag          329.795
Datsun 710             259.580
Hornet 4 Drive         426.135
Hornet Sportabout      590.310
Valiant                385.540
Duster 360             656.920
Merc 240D              270.980
Merc 230               299.570
Merc 280               350.460
Merc 280C              349.660
Merc 450SE             510.740
Merc 450SL             511.500
Merc 450SLC            509.850
Cadillac Fleetwood     728.560
Lincoln Continental    726.644
Chrysler Imperial      725.695
Fiat 128               213.850
Honda Civic            195.165
Toyota Corolla         206.955
Toyota Corona          273.775
Dodge Challenger       519.650
AMC Javelin            506.085
Camaro Z28             646.280
Pontiac Firebird       631.175
Fiat X1-9              208.215
Porsche 914-2          272.570
Lotus Europa           273.683
Ford Pantera L         670.690
Ferrari Dino           379.590
Maserati Bora          694.710
Volvo 142E             288.890
dtype: float64

In [85]:
mtcars.notnull().sum(axis=1)

Mazda RX4              11
Mazda RX4 Wag          11
Datsun 710             11
Hornet 4 Drive         11
Hornet Sportabout      11
Valiant                11
Duster 360             11
Merc 240D              11
Merc 230               11
Merc 280               11
Merc 280C              11
Merc 450SE             11
Merc 450SL             11
Merc 450SLC            11
Cadillac Fleetwood     11
Lincoln Continental    11
Chrysler Imperial      11
Fiat 128               11
Honda Civic            11
Toyota Corolla         11
Toyota Corona          11
Dodge Challenger       11
AMC Javelin            11
Camaro Z28             11
Pontiac Firebird       11
Fiat X1-9              11
Porsche 914-2          11
Lotus Europa           11
Ford Pantera L         11
Ferrari Dino           11
Maserati Bora          11
Volvo 142E             11
dtype: int64

In [86]:
32 * 11

352

In [87]:
mtcars.notnull().sum(axis=0).sum()

np.int64(352)

In [88]:
mtcars.max(axis=0)

mpg      33.900
cyl       8.000
disp    472.000
hp      335.000
drat      4.930
wt        5.424
qsec     22.900
vs        1.000
am        1.000
gear      5.000
carb      8.000
dtype: float64

In [89]:
mtcars.notnull().sum(axis=0).sum() #32*11

np.int64(352)

# Duplicates

In [93]:
mtcars = data('mtcars')
mtcars.head(2)

                mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

In [95]:
mtcars2 = mtcars.copy(). reset_index().rename(columns={'index':'car'})
mtcars2.head()

                 car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [96]:
mtcars2.shape

(32, 12)

In [107]:
mtcars2[mtcars2['car'] == 'Mazda RX4']

         car   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
0  Mazda RX4  21.0    6  160.0  110   3.9  2.62  16.46   0   1     4     4

In [121]:
mtcars2[mtcars2['cyl'] == 'Hornet 4 Drive'] #why the same data not showing for 'cyl'?

Empty DataFrame
Columns: [car, mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb]
Index: []

In [124]:
mazda2 = mtcars2[mtcars2['car'] == 'Mazda RX4']
datson2 = mtcars2[mtcars2['car'] == 'Datsun 710']

In [134]:
mtcars_dup = pd.concat([mtcars2, mazda2, datson2, mazda2], ignore_index=True)
mtcars_dup

                    car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2
32            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
33           Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
34            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4

In [138]:
mtcars.count()

mpg     32
cyl     32
disp    32
hp      32
drat    32
wt      32
qsec    32
vs      32
am      32
gear    32
carb    32
dtype: int64

In [133]:
mtcars_dup[mtcars_dup['car'] == 'Mazda Rx4']

Empty DataFrame
Columns: [car, mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb]
Index: []

In [130]:
mtcars_dup[mtcars_dup['car'] == 'Mazda Rx4']

Empty DataFrame
Columns: [car, mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb]
Index: []

In [127]:
mtcars.head()

                    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [128]:
mtcars_dup.shape

(35, 12)

In [129]:
mtcars_dup[mtcars_dup['car'] == 'Mazda Rx4']

Empty DataFrame
Columns: [car, mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb]
Index: []

In [135]:
mtcars_dup.duplicated().sum()

np.int64(3)

In [137]:
mtcars_dup.drop_duplicates()

                    car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [139]:
mtcars_dup.drop_duplicates(keep='first')

                    car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [140]:
mtcars_dup.drop_duplicates(keep='last')

                    car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2
33           Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
34            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4

In [141]:
mtcars_dup.drop_duplicates(keep=False)

                    car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

In [142]:
mtcars_dup[mtcars_dup.duplicated(subset = ['vs', 'am', 'gear', 'carb'])].sort_values(by=['gear','am','cyl','carb'])

                    car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
33           Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
32            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
34            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4

In [144]:
mtcars_dup[~ mtcars_dup.duplicated(subset = ['gear', 'am', 'cyl', 'carb'], keep=False)]

               car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
20   Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8

In [145]:
mtcars_dup.drop_duplicates(subset = ['gear', 'am', 'cyl', 'carb'], inplace=False)

                  car   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0           Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
2          Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3      Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4   Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
6          Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4
7           Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
9            Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
11         Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3
18        Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
20      Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
26      Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
28     Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4
29       Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
30      Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8

In [146]:
mtcars.head()

                    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [147]:
mtcars['mpg'].head()

Mazda RX4            21.0
Mazda RX4 Wag        21.0
Datsun 710           22.8
Hornet 4 Drive       21.4
Hornet Sportabout    18.7
Name: mpg, dtype: float64

In [148]:
mtcars.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb'], dtype='object')

In [149]:
mtcars[['wt', 'cyl', 'mpg', 'gear']].tail() #showing last few rows of data identified?

                   wt  cyl   mpg  gear
Lotus Europa    1.513    4  30.4     5
Ford Pantera L  3.170    8  15.8     5
Ferrari Dino    2.770    6  19.7     5
Maserati Bora   3.570    8  15.0     5
Volvo 142E      2.780    4  21.4     4

In [150]:
mtcars.iloc[0]

mpg      21.00
cyl       6.00
disp    160.00
hp      110.00
drat      3.90
wt        2.62
qsec     16.46
vs        0.00
am        1.00
gear      4.00
carb      4.00
Name: Mazda RX4, dtype: float64

In [152]:
mtcars.iloc[2]

mpg      22.80
cyl       4.00
disp    108.00
hp       93.00
drat      3.85
wt        2.32
qsec     18.61
vs        1.00
am        1.00
gear      4.00
carb      1.00
Name: Datsun 710, dtype: float64

In [153]:
mtcars.iloc[3:5]

                    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [154]:
mtcars.iloc[0:4]

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710      22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1

In [156]:
mtcars.iloc[[0,4]] #why showing row4 instead row5

                    mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
Mazda RX4          21.0    6  160.0  110  3.90  2.62  16.46   0   1     4     4
Hornet Sportabout  18.7    8  360.0  175  3.15  3.44  17.02   0   0     3     2

In [157]:
mtcars.head(5)

                    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [158]:
mtcars.loc['Datsun 710']

mpg      22.80
cyl       4.00
disp    108.00
hp       93.00
drat      3.85
wt        2.32
qsec     18.61
vs        1.00
am        1.00
gear      4.00
carb      1.00
Name: Datsun 710, dtype: float64

In [160]:
carlist = ['Mazda RX4', 'Datsun 710']
mtcars.loc[carlist]

             mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
Mazda RX4   21.0    6  160.0  110  3.90  2.62  16.46   0   1     4     4
Datsun 710  22.8    4  108.0   93  3.85  2.32  18.61   1   1     4     1

In [161]:
mtcars.loc[['Mazda RX4','Datsun 710']]

             mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
Mazda RX4   21.0    6  160.0  110  3.90  2.62  16.46   0   1     4     4
Datsun 710  22.8    4  108.0   93  3.85  2.32  18.61   1   1     4     1

In [162]:
mtcars.iloc[[0,2]]

             mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
Mazda RX4   21.0    6  160.0  110  3.90  2.62  16.46   0   1     4     4
Datsun 710  22.8    4  108.0   93  3.85  2.32  18.61   1   1     4     1

In [163]:
mtcars.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb'], dtype='object')

In [164]:
mtcars.loc[:, 'mpg':'wt'] #what is the meaning of : before 'mpg'

                      mpg  cyl   disp   hp  drat     wt
Mazda RX4            21.0    6  160.0  110  3.90  2.620
Mazda RX4 Wag        21.0    6  160.0  110  3.90  2.875
Datsun 710           22.8    4  108.0   93  3.85  2.320
Hornet 4 Drive       21.4    6  258.0  110  3.08  3.215
Hornet Sportabout    18.7    8  360.0  175  3.15  3.440
Valiant              18.1    6  225.0  105  2.76  3.460
Duster 360           14.3    8  360.0  245  3.21  3.570
Merc 240D            24.4    4  146.7   62  3.69  3.190
Merc 230             22.8    4  140.8   95  3.92  3.150
Merc 280             19.2    6  167.6  123  3.92  3.440
Merc 280C            17.8    6  167.6  123  3.92  3.440
Merc 450SE           16.4    8  275.8  180  3.07  4.070
Merc 450SL           17.3    8  275.8  180  3.07  3.730
Merc 450SLC          15.2    8  275.8  180  3.07  3.780
Cadillac Fleetwood   10.4    8  472.0  205  2.93  5.250
Lincoln Continental  10.4    8  460.0  215  3.00  5.424
Chrysler Imperial    14.7    8  440.0  230  3.23  5.345
Fiat 128             32.4    4   78.7   66  4.08  2.200
Honda Civic          30.4    4   75.7   52  4.93  1.615
Toyota Corolla       33.9    4   71.1   65  4.22  1.835
Toyota Corona        21.5    4  120.1   97  3.70  2.465
Dodge Challenger     15.5    8  318.0  150  2.76  3.520
AMC Javelin          15.2    8  304.0  150  3.15  3.435
Camaro Z28           13.3    8  350.0  245  3.73  3.840
Pontiac Firebird     19.2    8  400.0  175  3.08  3.845
Fiat X1-9            27.3    4   79.0   66  4.08  1.935
Porsche 914-2        26.0    4  120.3   91  4.43  2.140
Lotus Europa         30.4    4   95.1  113  3.77  1.513
Ford Pantera L       15.8    8  351.0  264  4.22  3.170
Ferrari Dino         19.7    6  145.0  175  3.62  2.770
Maserati Bora        15.0    8  301.0  335  3.54  3.570
Volvo 142E           21.4    4  121.0  109  4.11  2.780

In [167]:
KhulanCarlist = ['Mazda RX4', 'Datsun 710', 'Hornet 4 Drive']
print(KhulanCarlist)
mtcars.loc[KhulanCarlist, 'mpg':'wt'].head()

['Mazda RX4', 'Datsun 710', 'Hornet 4 Drive']

                 mpg  cyl   disp   hp  drat     wt
Mazda RX4       21.0    6  160.0  110  3.90  2.620
Datsun 710      22.8    4  108.0   93  3.85  2.320
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215

In [168]:
mtcars.loc[['Mazda RX4', 'Datsun 710', 'Hornet 4 Drive'], 'mpg':'wt'].head()

                 mpg  cyl   disp   hp  drat     wt
Mazda RX4       21.0    6  160.0  110  3.90  2.620
Datsun 710      22.8    4  108.0   93  3.85  2.320
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215

In [169]:
mtcars.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive', 'Hornet Sportabout',
       'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230', 'Merc 280', 'Merc 280C', 'Merc 450SE',
       'Merc 450SL', 'Merc 450SLC', 'Cadillac Fleetwood', 'Lincoln Continental',
       'Chrysler Imperial', 'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird', 'Fiat X1-9',
       'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L', 'Ferrari Dino', 'Maserati Bora',
       'Volvo 142E'],
      dtype='object')

In [170]:
mtcars.iloc[:, 3:8].head()

                    hp  drat     wt   qsec  vs
Mazda RX4          110  3.90  2.620  16.46   0
Mazda RX4 Wag      110  3.90  2.875  17.02   0
Datsun 710          93  3.85  2.320  18.61   1
Hornet 4 Drive     110  3.08  3.215  19.44   1
Hornet Sportabout  175  3.15  3.440  17.02   0

In [171]:
mtcars.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive', 'Hornet Sportabout',
       'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230', 'Merc 280', 'Merc 280C', 'Merc 450SE',
       'Merc 450SL', 'Merc 450SLC', 'Cadillac Fleetwood', 'Lincoln Continental',
       'Chrysler Imperial', 'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird', 'Fiat X1-9',
       'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L', 'Ferrari Dino', 'Maserati Bora',
       'Volvo 142E'],
      dtype='object')

In [172]:
mtcars.iloc[:, 3:8].head()

                    hp  drat     wt   qsec  vs
Mazda RX4          110  3.90  2.620  16.46   0
Mazda RX4 Wag      110  3.90  2.875  17.02   0
Datsun 710          93  3.85  2.320  18.61   1
Hornet 4 Drive     110  3.08  3.215  19.44   1
Hornet Sportabout  175  3.15  3.440  17.02   0

In [173]:
mtcars.iloc[1:10, [3,6,9,10]].head()

                    hp   qsec  gear  carb
Mazda RX4 Wag      110  17.02     4     4
Datsun 710          93  18.61     4     1
Hornet 4 Drive     110  19.44     3     1
Hornet Sportabout  175  17.02     3     2
Valiant            105  20.22     3     1

In [179]:
mtcars.iloc[1:11, [4,7,10,11]].head() #Check the error

IndexError: positional indexers are out-of-bounds

In [180]:
mtcars.iloc [0:3, [3,6,9,10]]

                hp   qsec  gear  carb
Mazda RX4      110  16.46     4     4
Mazda RX4 Wag  110  17.02     4     4
Datsun 710      93  18.61     4     1

In [184]:
mtcars.iloc [0,4,31], [3,6,9,10]].head()

SyntaxError: unmatched ']' (118654713.py, line 1)

In [186]:
mtcars.iloc [1,5,32], [4,7,10,11]]

SyntaxError: unmatched ']' (3643787027.py, line 1)

In [187]:
mtcars.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb'], dtype='object')